name: qsar
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - streamlit
  - pillow
  - scikit-learn
  - xgboost
  - matplotlib
  - seaborn
  - tqdm
  - pip
  - pip:
    - streamlit-ketcher
    - rdkit